functionsDirectory = "/Users/m4server/Documents/play/netlify/functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/m4server/Documents/play"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install"
functions = "/Users/m4server/Documents/play/netlify/functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/api/config"
to = "/.netlify/functions/config"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/stream-status"
to = "/.netlify/functions/stream-status"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/break-mode"
to = "/.netlify/functions/break-mode"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/mux-webhook"
to = "/.netlify/functions/mux-webhook"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/recordings"
to = "/.netlify/functions/recordings"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/debug-mux"
to = "/.netlify/functions/debug-mux"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]